mongodb-labs/drivers-atlas-testing

- astrolabe/configuration.py
> Use updated Atlas Organization name to match new Atlas API credentials

- .evergreen/config.yml
There doesn't seem to be an imminent need for all these test cases for Python. Testing CPython 2.7 and 3.8 is sufficient on Linux as is testing 3.7 on Windows. Also, we can defer adding testing for released versions (in this case 3.10.x) to a later time when the need presents itself - testing master is sufficient for the time being.
> Reduce number of test cases for PyMongo

- astrolabe/exceptions.py
- astrolabe/spec_runner.py
- astrolabe/utils.py
Closes #9 
See https://github.com/mongodb-labs/drivers-atlas-testing/issues/9#issuecomment-622610173 for rationale.
> Stop redirecting standard streams of the workload executor subprocess

- .evergreen/config.yml
- docs/source/faq.rst
- docs/source/integration-guide.rst
- integrations/python/pymongo/install-driver.sh
Closes #62 
Closes #48 (kind of - it doesn't actually solve this problem in a foolproof manner because if we add more platforms, we could end up running more than N concurrent builds where N is the maximum number of instances of `ubuntu1804-drivers-atlas-testing`).
> Migrate linux builds to ubuntu1804-drivers-atlas-testing

- .evergreen/config.yml
- .evergreen/run-mongodb.sh
- astrolabe/cli.py
- docs/source/integration-guide.rst
> Enable running workload executor validation as an evergreen patch-build

- .evergreen/config.yml
- integrations/node/install-driver.sh
- integrations/node/workload-executor
- integrations/node/workload-executor.js
Adds workload-executor integration for Node, and runtimes for the 3 most recent LTS versions of node (Carbon/v8, Dubnium/v10, Erbium/v12).
[evergreen patch](https://evergreen.mongodb.com/version/5ec6868dc9ec440628ee9129)
> node integration

- .evergreen/config.yml
- integrations/node/install-driver.sh
- integrations/node/workload-executor
- integrations/node/workload-executor.js
- Fixes a bug with duplicate IDs on insert by passing a copy of operation arguments instead of a reference
- Remove node_carbon runtime (no longer supported in driver version `4.0`/`master`)
- Print errors to stdout for easier future debugging
[Patch results](https://spruce.mongodb.com/version/5f10bd6da4cf472226e658b9/tasks)
> Fix node integration

- integrations/python/pymongo/workload-executor
> Bash scripts wrapping native workload executors need not run them as background processes

- docs/source/spec-workload-executor.rst
> Document clearly that workload executors MUST ignore the testData key in the workload specification

- .evergreen/config.yml
- astrolabe/cli.py
- astrolabe/configuration.py
- astrolabe/docgen.py
- astrolabe/utils.py
- atlasclient/client.py
- atlasclient/configuration.py
Closes #23 
With this change, the `astrolabe info default-values` and `astrolabe info environment-variables` help commands are both replaced with `astrolabe info configuration`. Output:
```
Astrolabe has many configurable options that can be set at runtime via the command-line, or using environment variables. The following table 
lists these configurable options, their default values, and the environment variables that can be used to specify them. 
Note that if an option is specified using an environment variable, and also via the command-line, the command-line value takes precedence.
====================  ===============================  ===================================  ======================================================
CLI Option            Environment Variable …
```
> Overhaul configuration option definition and management

- atlasclient/client.py
- atlasclient/configuration.py
This change allows us to specify the `apiVersion` portion of an Atlas API call at invocation (currently this is a configurable value but it can only be specified upon client initialization, not when issuing a request). The full URL generated is `<baseUrl>/<apiVersion>/<resourcePath>`.
To issue a command to the `private` API version, for example to retrieve logs, a user can now do:
```
client = AtlasClient(username=<username>, password=<password>)
response = client.nds.groups.project_id.clusters.cluster_name.get(api_version='private').data
```
> Make API version configurable when issuing a request

- .evergreen/config.yml
- integrations/java/install-driver.sh
- integrations/java/sync/install-driver.sh
- integrations/java/sync/workload-executor
- integrations/java/workload-executor
Probably just one reviewer is sufficient, but not sure who is should be.  Feel free to choose one and remove the other.
Patch build [here](https://evergreen.mongodb.com/build/drivers_atlas_testing_tests_java__driver~java_master_platform~ubuntu_18.04_runtime~java11_patch_86b7d46cdc738755009edbc2ca08b41d85d8d2f5_6050d98c850e61097b2f157c_21_03_16_16_15_22)
> Add workload executor for the synchronous Java driver

- astrolabe/exceptions.py
- astrolabe/runner.py
- astrolabe/utils.py
- astrolabe/validator.py
- tests/validator-numErrors-not-captured.yml
- tests/validator-numErrors.yml
- tests/validator-numFailures-as-errors.yml
- tests/validator-numFailures-not-captured.yml
- tests/validator-numFailures.yml
- tests/validator-simple.yml
Test that uncaptured errors and failures fail the test run.
This PR also adds sleeps on each iteration of validator scenarios to reduce the amount of logs produced and speed up validation (since astrolabe takes some time to parse the produced json files).
>  DRIVERS-828 add tests for uncaptured errors and failures

- astrolabe/cli.py
This proves to be useful while manually running astrolabe and debugging. Since it requires user-confirmation (due to `click.confirm`) it can only be used when using astrolabe interactively.
> Add CLI endpoint astrolabe to delete all clusters under a given Atlas Project

- .evergreen/config.yml
DRIVERS-1562
This enables weekly testing of all legacy driver testing suites. Drivers should be removed from this as they are added to the evergreen config in the main development branch.
I have run a smoke-screen test with the Go driver, which initiated the test sequence correctly but timed out due while waiting for the maintenance to complete. I've chalked that up to cloud-dev being cloud-dev and assume that the tests theoretically run. I could not find configuration that completely restores the previous behaviour of not testing against cloud-dev, but that may be a feasible option to work around the cloud-dev limitations.
I've configured this patch to run all integration tests so we have a baseline for what's passing and what's not.
@jyemin should Java be removed from this?
> [V1] DRIVERS-1562 Set up periodic execution of Atlas Maintenance Tests

- astrolabe/utils.py
- astrolabe/validator.py
- docs/source/spec-test-format.rst
- docs/source/spec-workload-executor.rst
- tests/validator-numErrors-as-failures.yml
- tests/validator-numErrors-not-captured.yml
- tests/validator-numErrors.yml
- tests/validator-numFailures-as-errors.yml
- tests/validator-numFailures.yml
https://jira.mongodb.org/browse/DRIVERS-1652
This should also address [DRIVERS-1604](https://jira.mongodb.org/browse/DRIVERS-1604).
> DRIVERS-1652: Clarify events.json and result.json produced by workload executor

- astrolabe/runner.py
Increases the timeout to 5 minutes to hopefully cover all of these failures.
> DRIVERS-1659 Increase timeout in testFailover operation

- astrolabe/runner.py
- astrolabe/utils.py
The `wait_for_planning` function can currently cause test timeouts due to a bug when interpreting `datetime` objects that contain no timezone information. Some functions attempt to localize those datetime objects, leading to unexpected timestamp offsets. See an example in a recent Astrolabe run log from a Windows machine:
```
[2022/04/18 05:43:27.390] INFO:astrolabe.runner:Cluster 9bb4e4c47d: last planned: 2022-04-18 05:43:12; wanted after: 2022-04-18 06:43:01.950541; waited for 0.0 sec
```
Note that "wanted after" should be the current time (as seen in the logger timestamp), but is actually an hour in the future due to the timestamp offset bug.
This bug can also be observed on a Windows Server machine (running a Bash shell):
```
$ date -u -Iseconds
2022-04-19T22:06:41+00:00
$ python …
```
> Always specify UTC timezone to prevent a DST offset bug.

- integrations/dotnet/install-driver.sh
.NET driver build can sometimes fail because the `dotnet` CLI install script fails to download. Example failure log:
```
[2022/04/20 18:20:38.508] + set -o errexit
[2022/04/20 18:20:38.508] + curl -sSL https://dot.net/v1/dotnet-install.ps1 -o integrations/dotnet/dotnet-install.ps1
[2022/04/20 18:21:25.636] curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
...
[2022/04/20 18:32:24.415] Could not execute because the specified command or file was not found.
[2022/04/20 18:32:24.415] Possible reasons for this include:
...
```
Improve reliability of the .NET `install-driver.sh` script by retrying the install script download up to 5 times.
> Add retry to downloading the dotnet install script.

- .evergreen/config.yml
- astrolabe/cli.py
- astrolabe/commands.py
- astrolabe/configuration.py
- astrolabe/docgen.py
- astrolabe/runner.py
- docs/source/installing-running-locally.rst
Improvements made:
* Searching by organization name is inefficient as you have to page (the code doesn't look like it's paging either) through thousands of organizations before finding a string match.  There's a high chance of naming collision too since name is not unique. 
* This will require all env variables to be updated to org id rather than org name
* Creates a new project per AtlasTestCase with the suffix being the epoch timestamp in seconds. Ex: [ERICATEST-1651857784](https://cloud-qa.mongodb.com/v2/627559788a1e082d1ad4bbfc#)
* Cleans up any old projects in the organizations that have an epoch timestamp that exceeds 12 hours from current time.
> CLOUDP-100718 Improve Astrolabe Testing

- .evergreen/config.yml
I wanted to run a patch to make sure adding `ConnectionInfo.server_id` to the monitoring events wouldn't break anything and in the process noticed we forgot to switch this before the PR got merged.
> use mongodb/rust main branch for Rust testing

- .evergreen/config.yml
- README.rst
- docs/source/installing-running-locally.rst
- docs/source/integration-guide.rst
- setup.py
[DRIVERS-2409](https://jira.mongodb.org/browse/DRIVERS-2409)
Increase the minimum Python version to 3.7 in all documentation. Also add a classifier for Python 3.9 in `setup.py`.
> DRIVERS-2409 Increase documented minimum Python version to 3.7

- astrolabe/validator.py
The validator test paths got messed up while resolving a merge conflict in https://github.com/mongodb-labs/drivers-atlas-testing/pull/141. This fixes them.
> Fix workload executor validator test paths.

- .evergreen/config.yml
- integrations/dotnet/install-driver.sh
- integrations/dotnet/workload-executor
[DRIVERS-2419](https://jira.mongodb.org/browse/DRIVERS-2419)
Update the .NET driver install and workload executor scripts to support building and running on Linux. Add an Ubuntu .NET build variant that only runs the Kind test tasks.
Changes:
* Add an .NET Ubuntu build variant that only runs the Kind test tasks.
* Update the `"run kind test"` function to allow overriding the standard connection string for the Kind cluster.
* Override the standard connection string for the .NET Kind test tasks because .NET doesn't currently support loading TLS certs or CA files from connection string params. Use `tlsInsecure=true` instead.
* Add Windows and Linux driver build and install commands to the .NET `install-driver.sh` script.
* Move Windows-specific environment variables to the Windows-only block …
> DRIVERS-2419 Run .NET Kind tests on Linux.

- .evergreen/config.yml
- integrations/java/sync/install-driver.sh
- integrations/java/sync/workload-executor
[DRIVERS-2420](https://jira.mongodb.org/browse/DRIVERS-2420)
The Java driver does not support the `tlsCertificateKeyFile` and `tlsCAFile` connection string parameters (see [JAVA-3066](https://jira.mongodb.org/browse/JAVA-3066)) and instead uses a "key store" to provide TLS certs and CAs to the JVM. Update the Java workload executor script to check for the `tlsCertificateKeyFile` and `tlsCAFile` connection string parameters and, if present, add them to key stores and point the JVM at those key stores.
> DRIVERS-2420 Use a keystore to provide TLS certs to the Java driver.

- astrolabe/atlas_runner.py
- astrolabe/cli.py
[DRIVERS-2363](https://jira.mongodb.org/browse/DRIVERS-2363)
Currently, some exceptions that can happen during the Atlas test environment setup are not marked as a setup failure and instead show up as a test failure. The cause is that the `SingleTestRunner` constructor performs a bunch of Atlas cluster provisioning work as well as the `run()` method, but the constructor has no exception handling. To resolve that, move all Atlas "run-one" exception handling and "status" file writing into `cli.py`, and add exception handling to calling the `SingleTestRunner` constructor.
Changes:
* Catch all exceptions that happen while calling the `SingleTestRunner` constructor and mark them as "cloud-failure".
* Move all Atlas "run-one" exception handling into `cli.py` instead of `atlas_runner.py`.
* Move …
> DRIVERS-2363 Mark all Atlas test setup exceptions as 'cloud-failure'.

- integrations/dotnet/install-driver.sh
The .NET driver started failing recently (e.g. [here](https://evergreen.mongodb.com/lobster/evergreen/task/drivers_atlas_testing_tests_dotnet_linux__driver~dotnet_master_platform~ubuntu_18.04_runtime~dotnet_async_netcoreapp2.1_kind_reads_baseline_631825530305b9103d6b7d46_22_09_07_05_00_03/0/task#bookmarks=0%2C206&l=1)) with an error message like:
```
error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/mongo-csharp-driver/tests/MongoDB.Bson.Tests/MongoDB.Bson.Tests.csproj]
```
It seems to be related to https://github.com/mongodb/mongo-csharp-driver/pull/873, which updates the target framework for the `MongoDB.Bson.Tests.csproj` file.
Update the .NET build script to download …
> Update .NET build SDK version to 6.0

- integrations/ruby/executor.rb
[DRIVERS-2434](https://jira.mongodb.org/browse/DRIVERS-2434)
https://github.com/mongodb/mongo-ruby-driver/pull/2598 renamed the Ruby Driver unified test runner method `create_entities` to `create_spec_entities`. Update the call in the Ruby workload executor to use the new method name.
Note that https://github.com/mongodb/mongo-ruby-driver/pull/2619 will fix the other outstanding Ruby integration failures.
> DRIVERS-2434 Fix Ruby Driver unified spec test runner integration.

- .evergreen/config.yml
- tests/kubernetes/kind/upgrade.yml
- workloads/reads.yml
- workloads/writes.yml
[DRIVERS-2263](https://jira.mongodb.org/browse/DRIVERS-2263)
Add a Kind test case that upgrades the server version from 5.0.8 to 5.0.12. Assert that reads and writes (with retry enabled) can continue successfully during the upgrade.
Also add some delay to the read and write loops so that the number of events collected doesn't become unreasonably large, especially for the local Kind cluster where the round trip time is very short.
> DRIVERS-2263 Add a Kind test case for server version upgrade.

- kubernetes/kind/mongodb.yml
- tests/kubernetes/kind/upgrade.yml
[DRIVERS-2263](https://jira.mongodb.org/browse/DRIVERS-2263)
The Kind "upgrade" test added in https://github.com/mongodb-labs/drivers-atlas-testing/pull/150 depends on the "base" server version used in the Kind cluster being 5.0.8. Add comments that describe the link between the server version used in the Kind "upgrade" test [here](https://github.com/mongodb-labs/drivers-atlas-testing/blob/329efdddd568e486d5f2a8c60b5a9db5067db0df/tests/kubernetes/kind/upgrade.yml#L7) and the server version used in the "base" Kind cluster [here](https://github.com/mongodb-labs/drivers-atlas-testing/blob/329efdddd568e486d5f2a8c60b5a9db5067db0df/kubernetes/kind/mongodb.yml#L21).
> DRIVERS-2263 Add comments describing the required server versions for the 'upgrade' test.

- .evergreen/config.yml
Evergreen "cleans up" processes and Docker state changes between tasks, so all commands that depend on those processes or Docker state changes must be run in the same task. From the [Evergreen CI repo wiki](https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#task-groups):
> [B]y default, processes and Docker state changes (e.g. containers, images, volumes) are cleaned up between each task's execution.
Run all functions that create, modify, or otherwise rely on the Kind cluster in the same task.
> DRIVERS-2424 Fix and re-enable Kind logs download.

- .evergreen/config.yml
The work to re-enable the Node integration is tracked in [NODE-3049](https://jira.mongodb.org/browse/NODE-3049). Add that ticket number to the `TODO` comment for re-enabling the Node integration in the Evergreen config.
> Add the relevant NODE ticket to the TODO comment for re-enabling the Node integration.

- .evergreen/config.yml
- tests/kubernetes/kind/scaleDown.yml
[DRIVERS-2263](https://jira.mongodb.org/browse/DRIVERS-2263)
Add a Kind test case that scales the number of replica set nodes from 3 to 1. Assert that reads and writes (with retry enabled) can continue successfully during the scale-down.
> DRIVERS-2263 Add a Kind test case for replica set scale down.

- .evergreen/config.yml
[DRIVERS-2460](https://jira.mongodb.org/browse/DRIVERS-2460)
The version of Python that ships with the v4 "mongodbtoolchain" is now Python 3.10. Use a Python toolchain in `/opt/python` instead of `/opt/mongodbtoolchain` so we use a consistent version of Python.
Also remove the unnecessary `PYTHON_BINARY` variables from the Java and Go runtime axes.
> DRIVERS-2460 Use python3 toolchain in /opt/python/ instead of /opt/mongodbtoolchain/

- astrolabe/atlas_runner.py
- atlasclient/configuration.py
[CLOUDP-123702](https://jira.mongodb.org/browse/CLOUDP-123702)
This addresses the two remaining failure cases relevant to the original ticket.
Group not found during clean_old_projects:
https://evergreen.mongodb.com/task/drivers_atlas_testing_tests_ruby__driver~ruby_master_platform~ubuntu_18.04_runtime~python39_atlas_retryReads_primaryTakeover_633a6c54d6d80a2daf4a35b1_22_10_03_05_00_04
And http timeout while ensuring project:
https://evergreen.mongodb.com/task/drivers_atlas_testing_tests_python_windows__driver~pymongo_master_platform~windows_64_runtime~python37_windows_atlas_retryReads_move_sharded_63391ad1c9ec443c49aa2150_22_10_02_05_00_01
> CLOUDP-123702: Increase Atlas http timeout to 30 sec and handle group cleanup exception

- workloads/README.rst
Fixes broken syntax introduced in https://github.com/mongodb-labs/drivers-atlas-testing/commit/74c1c750f4941c690cf41773af16ad95dd957bbd.
> Fix RST syntax

- astrolabe/atlas_runner.py
Sometimes the `astrolabe` CLI will exit when polling for Atlas cluster status due to an HTTP call timeout. An example exception output is:
```
atlasclient.exceptions.AtlasClientError: HTTPSConnectionPool(host='cloud-qa.mongodb.com', port=443): Read timed out. (read timeout=30.0) (GET https://cloud-qa.mongodb.com/api/atlas/v1.0/groups/639e9f7f25930c386c4e5ad3/clusters/4ba448af53)
```
Those HTTP call timeouts seem to be intermittent, so we should retry the call again instead of allowing the CLI to exit.
> Catch and retry HTTP timeouts that happen while polling for cluster state.

- astrolabe/validator.py
The [documentation](https://github.com/mongodb-labs/drivers-atlas-testing/blob/3d5a29150e463ecb58179912ef24729b541a9347/astrolabe/validator.py#L130) for `assert_events` states:
> Based on the corresponding parameter for each field, the function will then assert either that the array is empty or that it is non-empty and each document therein has an expected structure.
And [within the function](https://github.com/mongodb-labs/drivers-atlas-testing/blob/3d5a29150e463ecb58179912ef24729b541a9347/astrolabe/validator.py#L164):
> If hasEvents is true, assert that the array is non-empty and that each object within contains essential fields. If hasEvents is false, the array should be empty.
>
> Note: we do not assert the type of events observed since not all drivers implement CMAP and thus might …
> DRIVERS-1660 Remove assertions for types of workload executor events

- .evergreen/config.yml
- integrations/c/install-driver.sh
- integrations/c/workload-executor
This PR adds integration files to support testing with the [C Driver](https://github.com/mongodb/mongo-c-driver).
Addresses [CDRIVER-3869](https://jira.mongodb.org/browse/CDRIVER-3869) and is related to https://github.com/mongodb/mongo-c-driver/pull/1220.
Verified by [this patch](https://spruce.mongodb.com/version/640f8e347742aee833e8e489/tasks).
Two "runtimes" are added to the config: one that builds with GCC and one that builds with Clang. The GCC build generates coredumps on assertion failures; the Clang build compiles with ASAN/UBSAN for runtime checks. Only the Ubuntu 18.04 distro is tested (notably does not test on Windows or macOS).
Only the minimum required CMake configuration variables are set:
- CMAKE_BUILD_TYPE: RelWithDebInfo.
- ENABLE_AUTOMATIC_INIT_AND_CLEANUP: OFF (ON is …
> CDRIVER-3869 Add C Driver Integration

- integrations/rust/workload-executor
This is a minor update in the Rust workload executor to account for a change in a test in the driver.
succeeding patch: https://spruce.mongodb.com/version/646522b23e8e86cb9db2133b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Run ignored test in Rust script

- integrations/c/install-driver.sh
Addresses ongoing task failures due to conflict with ASAN when building with Clang. Verified by [this patch](https://spruce.mongodb.com/version/64c950553627e05542834120).
> Avoid C Driver task failures due to ENABLE_EXTRA_ALIGNMENT

- .evergreen/config.yml
- integrations/go/go.mod
- integrations/go/install-driver.sh
- integrations/go/workload_executor_test.go
[GODRIVER-2919](https://jira.mongodb.org/browse/GODRIVER-2919)
* Fix the missing parameter in the `ParseTestFile` function call.
* Use valid `go.mod` and `go.sum` configs to make working on the Go Driver integration files easier (allows the Go language server to work properly). The Go driver integration "install" script still updates to the latest revision of the Go driver.
* Update Go version to 1.20
> GODRIVER-2919 Fix the Go driver integration and update to Go 1.20

- .evergreen/config.yml
failure.yml was removed but still expected in the evergreen config.
> test(DRIVERS-2700): remove failure also from evg run

- integrations/node/install-driver.sh
Fixes npm failures by pinning npm to version 9 which still supports Node 16
> fix(NODE-5602): fix node npm install

- .evergreen/config.yml
- astrolabe/atlas_runner.py
- astrolabe/cli.py
The clusters were silently failing to delete because they were trying to delete the cluster in `drivers-atlas-testing` instead of the the newly created project.
> DRIVERS-2715 Investigate Increased Costs of Drivers Atlas QA Usage

- .evergreen/config.yml
- integrations/dotnet/install-driver.sh
- integrations/dotnet/workload-executor
.NET Core 2.x is EOL and Microsoft removed the binaries from the download location. Switching to .NET 6 since it is an LTS release.
WARNING: I was unsuccessful in running `astrolabe` locally. So these changes are currently untested. If there are any issues, please let me know and I can investigate.
> Switched Astrolabe to run on .NET 6.

- .evergreen/config.yml
- astrolabe/cli.py
- setup.py
Verified with https://spruce.mongodb.com/task/drivers_atlas_testing_tests_python__driver~pymongo_master_platform~ubuntu_18.04_runtime~python39_atlas_retryReads_move_patch_fca5526934ffbc67d485b8ec0960e843b85db9d8_6511dfcac9ec44bf4d8f36f9_23_09_25_19_30_27/logs?execution=0 that no projects remained open.
> DRIVERS-2734 Ensure projects are deleted along with the cluster

- .evergreen/config.yml
- astrolabe/atlas_runner.py
- astrolabe/cli.py
- setup.py
Use a timestamp in the project name so the `clean_old_projects` function can remove previous projects after the fact.
> DRIVERS-2645 Use clean_old_projects to delete projects

- .evergreen/config.yml
Handle change of EVG runner behavior:
`Skipping Atlas cluster cleanup because it's not a Atlas task.`
https://spruce.mongodb.com/task/drivers_atlas_testing_tests_python__driver~pymongo_master_platform~ubuntu_18.04_runtime~python39_atlas_retryReads_primaryRemoval_652f6652306615a81bf1b179_23_10_18_05_00_02/logs?execution=0
> DRIVERS-2745 Handle variable expansions

- .evergreen/config.yml
- .evergreen/run-mongodb.sh
Uses the newly created Ubuntu 22 distro to run tests for Node 18 and 20 and updates the MongoDB server version to latest to be able to run against both Ubuntu 18 and 22. Also updates server version from 4.2 to latest to be able to run on both Ubuntu versions. (4.2 does not exist on Ubuntu 22 - 6.0 is lowest)
Startup times for various languages have increased so updated times where appropriate.
> test(NODE-5598): add node 18 and 20 to matrix

- .evergreen/config.yml
[DRIVERS-2786](https://jira.mongodb.org/browse/DRIVERS-2786)
Use the `retryWrites.yml` workload file for the "kind-retryWrites-scaleDown" task.
> DRIVERS-2786 Enable retryable writes for kind-retryWrites-scaleDown test.

- integrations/go/install-driver.sh
GODRIVER-3069
The cmd package is internalized on the master branch in GODRIVER-2724 . The Go integration needs to be updated to use v1.
> GODRIVER-3069 Update Go integration to use V1

- .evergreen/config.yml
- astrolabe/cli.py
Following the description on [DRIVERS-2729](https://jira.mongodb.org/browse/DRIVERS-2729), I've: 
* Added `post_error_fails_task = true` 
* Re-raise the exception on failures
what would be the expected exception type I'd raise for when the project name is not found?
> DRIVERS-2729: Make Astrolabe failure-to-cleanup more obvious

- docs/faq.md
- docs/integration-guide.md
- docs/spec-workload-executor.md
This follows the recent renaming of the default branch in GitHub.
> Rename references to old branch name

- .evergreen/config.yml
- .evergreen/run-mongodb.sh
DRIVERS-2726
I skipped node 16 as well as the .NET driver as that had issues in my testing and should be updated separately. I ran a patch with a single Atlas and a single Kind task, which all passed successfully: https://spruce.mongodb.com/version/6530f40e9ccd4e89b0cdcf5c
> DRIVERS-2726: Use Ubuntu 22.04

- integrations/python/pymongo/workload-executor.py
Reverts mongodb-labs/drivers-atlas-testing#201
This appears to be causing failures in recent runs.
> Revert "PYTHON-2723 Run the PyMongo Test Class Setup Function"

- .evergreen/config.yml
- .evergreen/run-mongodb.sh
- integrations/python/pymongo/install-driver.sh
- kubernetes/kind/create.sh
In #211 I observed failures when running the validator. This seems to happen because Astrolabe uses `sh` to call run-mongodb.sh and subsequently call run-orchestration.sh. This PR changes scripts to use `bash` where not already in use.
Note: the PHP failure is fixed by #211, but I wanted to separate the pull requests. The .NET failure has been a consistent failure for a while.
> Use bash shell where not already in use

- astrolabe/atlas_runner.py
[DRIVERS-2964](https://jira.mongodb.org/browse/DRIVERS-2964)
We want to collect more information about the cluster state when the "assertPrimaryRegion" step fails, so instead of immediately stopping the job, log the cluster state every 5 seconds for the next 30 minutes (then stop the job).
> DRIVERS-2964 Log cluster state for 30 minutes after assertPrimaryRegion failure.

- astrolabe/atlas_runner.py
[DRIVERS-2964](https://jira.mongodb.org/browse/DRIVERS-2964)
The goal is to reduce the noise of known failures while still providing the logging to help us debug the issue.
> DRIVERS-2964 Check primary region again after waiting for 30 minutes on assertPrimaryRegion failure.

- integrations/php/install-driver.sh
- integrations/php/workload-executor.php
Follow https://github.com/mongodb/mongo-php-library/pull/1413
> Remove code specific to symfony/phpunit-bridge to use PHPUnit directly from vendors

- .evergreen/config.yml
- README.md
- docs/installing-running-locally.md
- docs/integration-guide.md
- integrations/python/pymongo/install-driver.sh
- integrations/python/pymongo/workload-executor.py
- pyproject.toml
Depends on https://github.com/mongodb/mongo-python-driver/pull/1924
> Update to support PyMongo 4.11

- .evergreen/config.yml
- .evergreen/run-mongodb.sh
- .evergreen/setup-secrets.sh
- .gitignore
- astrolabe/cli.py
- docs/installing-running-locally.md
Move all secrets except the `atlas_admin_api_password` to an AWS vault.   That secret should not be shared amongst driver teams.
> DRIVERS-3020 Remove use of Evergreen secrets in Atlas Testing

- .evergreen/config.yml
- integrations/python/pymongo/install-driver.sh
- integrations/python/pymongo/workload-executor
Some workload executors need additional environment variables:
- Python needs `PYTHON_BIN_DIR`
- .NET needs `ASYNC` and `FRAMEWORK`
- Java needs `JAVA_HOME`
Add those to the expansions list for the "run atlas test" function.
> Fix missing workload executor expansions in test runner function.

- .evergreen/config.yml
On some tests the workload executor was exiting before the Node tests could start - upped this to 60 seconds now.
Patch with our previous flaky tests: https://spruce.mongodb.com/version/673606d16bb65200075673a1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
It seems some drivers are failing the workload validator tests that run on PRs only. Those failures are unrelated to Node and its validation tests are passing.
> test: increase node startup timeout
