- .evergreen/config.yml
- astrolabe/cli.py
- astrolabe/spec_runner.py
- astrolabe/utils.py
> Ensure Atlas clusters are marked for deletion at the end of Evergreen build

- .evergreen/config.yml
- astrolabe/spec_runner.py
- astrolabe/utils.py
- setup.py
> Add support for running Atlas Planned Maintenance Tests on Windows

- .evergreen/python/pymongo/install-driver.sh
- .evergreen/python/pymongo/workload-executor.py
> Fix Pymongo's integration on Windows

- docs/source/index.rst
- docs/source/integration-guide.rst
- docs/source/spec-test-format.rst
- docs/source/technical-design.rst
- tests/README.rst
> Move test format specification into a separate file

- docs/source/index.rst
- docs/source/integration-guide.rst
- docs/source/spec-workload-executor.rst
- docs/source/technical-design.rst
> Add Workload Executor Behavioral Description to Integration Guide

- astrolabe/docgen.py
- atlasclient/client.py
- docs/source/installing-running-locally.rst
> Add debug logging to atlasclient requests and responses

- astrolabe/cli.py
- astrolabe/commands.py
- astrolabe/configuration.py
- astrolabe/docgen.py
- astrolabe/spec_runner.py
- docs/source/installing-running-locally.rst
> Use 'Project' instead of 'Group' everywhere

- .evergreen/python/pymongo/workload-executor.py
- astrolabe/spec_runner.py
- astrolabe/utils.py
- docs/source/spec-workload-executor.rst
> Report workload statistics using a file instead of using stderr

- astrolabe/cli.py
- atlasclient/client.py
- docs/source/faq.rst
- docs/source/index.rst
> Stop requiring Atlas API credentials for all astrolabe commands

- astrolabe/cli.py
- astrolabe/spec_runner.py
- astrolabe/utils.py
- astrolabe/workload_executor_validator.py
- docs/source/spec-workload-executor.rst
- integrations/python/pymongo/workload-executor.py
> Add command to validate workload executors

- astrolabe/runner.py
- astrolabe/utils.py
- integrations/python/pymongo/workload-executor.py
> Only inject CA certificates from certifi if using a mongob+srv URI

- .evergreen/config.yml
- astrolabe/cli.py
- astrolabe/configuration.py
- astrolabe/runner.py
- astrolabe/utils.py
- astrolabe/validator.py
- docs/source/faq.rst
- docs/source/integration-guide.rst
- docs/source/technical-design.rst
Closes #69 
Patch: https://evergreen.mongodb.com/version/5eb3517c2fbabe21246b0a3f
> Add a parameter that tells astrolabe how long to wait for the workload executor to start running operations

- astrolabe/validator.py
> Make workload executor validation more permissive 

- .evergreen/config.yml
- integrations/dotnet/install-driver.sh
- integrations/dotnet/workload-executor
JIRA: https://jira.mongodb.org/browse/CSHARP-2515
Evergreen: https://evergreen.mongodb.com/version/5f5689e2c9ec4454b69dc4ea
Native PR: https://github.com/MikalaiMazurenka/mongo-csharp-driver/pull/56
> CSHARP-2515: Test Planned Maintenance Scenarios in Drivers

- astrolabe/runner.py
> Astrolabe should exit early when cluster initialization fails

- tests/retryReads-move-sharded.yml
- tests/retryReads-move.yml
- tests/retryReads-primaryRemoval.yml
- tests/retryReads-primaryTakeover.yml
- tests/retryReads-processRestart-sharded.yml
- tests/retryReads-processRestart.yml
- tests/retryReads-resizeCluster.yml
- tests/retryReads-testFailover-sharded.yml
- tests/retryReads-testFailover.yml
- tests/retryReads-toggleServerSideJS.yml
- tests/retryReads-vmRestart-sharded.yml
- tests/retryReads-vmRestart.yml
- tests/retryWrites-resizeCluster.yml
- tests/retryWrites-toggleServerSideJS.yml
- tests/validator-numErrors.yml
- tests/validator-numFailures-as-errors.yml
- tests/validator-numFailures.yml
- tests/validator-simple.yml
https://jira.mongodb.com/browse/-828
>  DRIVERS-828 use the correct schema version

- docs/source/spec-test-format.rst
- tests/retryReads-move-sharded.yml
- tests/retryReads-move.yml
- tests/retryReads-primaryRemoval.yml
- tests/retryReads-primaryTakeover.yml
- tests/retryReads-processRestart-sharded.yml
- tests/retryReads-processRestart.yml
- tests/retryReads-resizeCluster.yml
- tests/retryReads-testFailover-sharded.yml
- tests/retryReads-testFailover.yml
- tests/retryReads-toggleServerSideJS.yml
- tests/retryReads-vmRestart-sharded.yml
- tests/retryReads-vmRestart.yml
- tests/retryWrites-resizeCluster.yml
- tests/retryWrites-toggleServerSideJS.yml
- tests/validator-simple.yml
Related to mongodb/specifications#921 and #104
cc: @DmitryLukyanov
> DRIVERS-828 Use array of objects for storeEventsAsEntities

- astrolabe/runner.py
DRIVERS-1585
I deviated from the ticket and have opted for a timeout of 90 seconds as that's the value that's used elsewhere. Happy to change it if you feel 90 seconds isn't enough.
> DRIVERS-1585 Retry testFailover operations until they succeed

- .evergreen/config.yml
https://jira.mongodb.com/browse/-828
>  DRIVERS-828 fix log uploading

- astrolabe/poller.py
- astrolabe/runner.py
- astrolabe/timer.py
- astrolabe/utils.py
https://jira.mongodb.com/browse/DRIVERS-828
> DRIVERS-828 improve diagnostics and retry log collection

- .evergreen/config.yml
- integrations/php/composer.json
- integrations/php/install-driver.sh
- integrations/php/workload-executor
- integrations/php/workload-executor.php
https://jira.mongodb.org/browse/PHPLIB-646
Related to mongodb/mongo-php-library#806.
Patch build: https://spruce.mongodb.com/version/60807a3dd1fe0765255b0bbd/tasks
> PHPLIB-646: PHP workload executor

- .evergreen/config.yml
- astrolabe/utils.py
- integrations/dotnet/install-driver.sh
- integrations/dotnet/workload-executor
These changes **must not** be merged until the related .dotnet driver changes will be merged
> CSHARP-3341: Comprehensive test scenario suite for planned maintenance.

- astrolabe/atlas_runner.py
[DRIVERS-2418](https://jira.mongodb.org/browse/DRIVERS-2418)
For some reason, the JUnit test results for the "expect failure" tasks were not uploaded before https://github.com/mongodb-labs/drivers-atlas-testing/pull/155 was merged, so the tasks passed despite the JUnit test output being marked failure. Update the JUnit test results to only indicate failure if "expect failure" and the actual failure do not match.
> DRIVERS-2418 Fix JUnit output to only indicate failure when failure isn't expected.

- astrolabe/validator.py
I came across this while reviewing #162.
> Fix typo in error message

- integrations/php/workload-executor.php
https://jira.mongodb.org/browse/PHPLIB-1020
Patch build: https://spruce.mongodb.com/version/64bb24d8e3c331ca539f4316/tasks
> PHPLIB-1020: Disable serverSelectionTryOnce for PHP workloads

- astrolabe/cli.py
`error_code` is a string, `status_code` is the integer.
> DRIVERS-2715 Ensure project is deleted

- atlasclient/utils.py
[Evergreen patch as smoke test](https://spruce.mongodb.com/version/65c389cc2a60ed3d716a7354/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
> DRIVERS-2815: [bugfix]: logger = logging.getLogger(__name__)

- .evergreen/config.yml
- integrations/dotnet/install-driver.sh
- integrations/dotnet/workload-executor
Also fixes current setup failure.
> CSHARP-5005: Add .NET 8 tests to Astrolabe

- astrolabe/atlas_runner.py
[DRIVERS-2964](https://jira.mongodb.org/browse/DRIVERS-2964)
Increase the delay before checking for cluster idle status after making a config update. It's not clear why it's taking so long for the cluster status to become non-idle after issuing a config update, so the new value of 15s (up from 5s) may not suffice forever if the underlying cause of the delay gets worse. See [PRODTRIAGE-1232](https://jira.mongodb.org/browse/PRODTRIAGE-1232) for some background.
Also include the full replica set member list in the exception thrown when `assertPrimaryRegion` is unsuccessful.
> DRIVERS-2964 Log more information and increase wait time before idle check.

- .evergreen/config.yml
The development branches for PHP have changed, this PR updates them to the new values.
> Update PHP branch name

- .evergreen/config.yml
> Rename mongo-java driver branch from master to main

- integrations/python/pymongo/workload-executor.py
Also fixes nightly failures we have been seeing in PyMongo.
> PYTHON-4863 Fix python workload execution

- .evergreen/config.yml
- integrations/python/pymongo/workload-executor.py
Passing build: https://spruce.mongodb.com/version/6777c8d4169c870007265633/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-4863 Fix python connection string handling
